"""message

Revision ID: a6cec37fc2b6
Revises: 0003
Create Date: 2026-03-24 14:54:51.636263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6cec37fc2b6'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('additional_services', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('additional_services', 'icon',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('additional_services', 'desc',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_additional_services_id'), 'additional_services', ['id'], unique=False)
    op.alter_column('available_discounts', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('available_discounts', 'max_days',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_index(op.f('ix_available_discounts_id'), 'available_discounts', ['id'], unique=False)
    op.add_column('cars', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_deals_car_id'), 'deals', ['car_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_user_id'), 'deals', ['user_id'], unique=False)
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_deals_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_car_id'), table_name='deals')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_column('cars', 'category')
    op.drop_index(op.f('ix_available_discounts_id'), table_name='available_discounts')
    op.alter_column('available_discounts', 'max_days',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('available_discounts', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_additional_services_id'), table_name='additional_services')
    op.alter_column('additional_services', 'desc',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('additional_services', 'icon',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('additional_services', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
